#!/usr/bin/env bash

$HOME/bin/${SHELLINABOX_WRAPPER_SCRIPT_NAME:-'start_shellinabox.sh'} &
shellinabox_pid=$!

$HOME/bin/${DROPBOX_RESTORE_SCRIPT_NAME:-'restore_dropbox.sh'}

if [ ! -e $HOME/serverfiles/eula.txt ]
then
  mkdir -p $HOME/serverfiles
  echo 'eula=true' > $HOME/serverfiles/eula.txt
fi

$HOME/bin/${REFRESH_WRAPPER_SCRIPT_NAME:-'start_refresh.sh'} &

limit=$(ulimit -u)
case $limit in
  512)   # 2X Dyno
  heap="768m"
  ;;
  32768) # PX Dyno
  heap="4g"
  ;;
  *)     # 1X Dyno
  heap="384m"
  ;;
esac

heap="1024m"

cd $HOME/serverfiles
eval "screen -L -h 2048 -dmS minecraft java -Xmx${heap} -Xms${heap} -jar ../minecraft.jar nogui"
minecraft_pid=$!

screen -X "logfile 1" && sleep 1
eval "tail -f screenlog.0 &"
tail_pid=$!

$HOME/bin/${DROPBOX_STARTUP_SCRIPT_NAME:-'start_continuous_backup_dropbox.sh'} &
dropbox_pid=$!

if [ -f /app/.pktriot/config.json ]
then
$HOME/bin/${PKTRIOT_WRAPPER_SCRIPT_NAME:-'start_pktriot.sh'} &
else
$HOME/bin/${NGROK_WRAPPER_SCRIPT_NAME:-'start_ngrok.sh'} &
fi
tunnel_pid=$!

trap "echo 'received signal to turn off.'; kill $tunnel_pid $shellinabox_pid $dropbox_pid $tail_pid; screen -S mincraft -p 0 -X eval 'stuff /stop\015'; $HOME/bin/${DROPBOX_BACKUP_SCRIPT_NAME:-'backup_dropbox.sh'}; exit" SIGTERM SIGINT
trap "kill -9 $tunnel_pid $shellinabox_pid $dropbox_pid $tail_pid $minecraft_pid; exit" SIGKILL

while true; do sleep 1; done
